ALTER TABLE order ADD COLUMN deletedAt TIMESTAMP DEFAULT NULL;
ALTER TABLE orderline ADD COLUMN deletedAt TIMESTAMP DEFAULT NULL;
ALTER TABLE product ADD COLUMN deletedAt TIMESTAMP DEFAULT NULL;
ALTER TABLE proposal ADD COLUMN deletedAt TIMESTAMP DEFAULT NULL;
ALTER TABLE proposalline ADD COLUMN deletedAt TIMESTAMP DEFAULT NULL;
ALTER TABLE user ADD COLUMN deletedAt TIMESTAMP DEFAULT NULL;
