insert into organization (id, name, legalName, cuit, role) values (1, 'Hayes-Lubowitz', 'Safeway Inc.', '31-56302898-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (2, 'Gaylord Group', 'KMART CORPORATION', '17-86235065-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (3, 'Schoen, Sporer and Schuppe', 'BioActive Nutritional', '65-43215618-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (4, 'Wolff Group', 'Major Pharmaceuticals', '61-21148864-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (5, 'Armstrong-Lind', 'NUGA MEDICAL CO., LTD.', '50-46817905-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (6, 'Gorczany Group', 'ABLE C&C CO., LTD.', '56-54690801-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (7, 'Abshire Inc', 'Mylan Institutional LLC', '61-05839066-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (8, 'Hegmann-Reinger', 'Jafra Cosmetics International Inc', '77-19618604-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (9, 'Hudson LLC', 'BluePoint Laboratories', '99-00087057-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (10, 'Cremin-Robel', 'Lake Erie Medical DBA Quality Care Products LLC', '43-78253726-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (11, 'Bins and Sons', 'Uriel Pharmacy Inc.', '58-66701675-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (12, 'Wolff LLC', 'Unit Dose Services', '70-99989906-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (13, 'Schowalter Group', 'HOMEOLAB USA INC', '08-31347698-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (14, 'Spencer and Sons', 'ALK-Abello, Inc.', '98-82126062-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (15, 'Haley LLC', 'REMEDYREPACK INC.', '00-98233133-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (16, 'Cruickshank and Sons', 'Major Pharmaceuticals', '85-25630991-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (17, 'Lang Inc', 'THEFACESHOP CO., LTD', '08-38651826-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (18, 'Casper, Weber and Denesik', 'Innovation Specialties', '23-53488805-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (19, 'Flatley, Wiza and Hartmann', 'StarCap Medical Private Limited', '06-74575545-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (20, 'Kuvalis, Wisoky and Davis', 'Cardinal Health', '68-03763316-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (21, 'Hammes LLC', 'Blenheim Pharmacal, Inc.', '78-48051611-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (22, 'Johnston-Howell', 'American Sales Company', '57-34313091-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (23, 'Koelpin, Conroy and Yost', 'Safeway', '58-41016277-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (24, 'Smith, Roberts and Effertz', 'AstraZeneca LP', '47-62556321-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (25, 'Tromp LLC', 'Cape Medical Supply, Inc', '95-69025036-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (26, 'Walker Group', 'Apotheca Company', '84-18526442-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (27, 'Beatty, Greenfelder and Hyatt', 'Physicians Total Care, Inc.', '17-51728417-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (28, 'Gorczany, McLaughlin and Gusikowski', 'Mallinckrodt, Inc.', '84-62613277-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (29, 'Stark and Sons', 'ReadyMeds', '81-48240343-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (30, 'O''Connell-Franecki', 'Life Line Home Care Services, Inc.', '54-72253176-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (31, 'Hessel Inc', 'BluePoint Laboratories', '15-84302267-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (32, 'Pacocha Group', 'Meijer Distribution Inc', '20-93781054-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (33, 'Sauer, Fay and Baumbach', 'NCS HealthCare of KY, Inc dba Vangard Labs', '41-16051262-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (34, 'Erdman, Ortiz and Hackett', 'Breckenridge Pharmaceutical, Inc.', '82-23469023-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (35, 'Brekke Group', 'Physicians Total Care, Inc.', '79-52877002-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (36, 'Schimmel, Gorczany and Gaylord', 'McKesson Contract Packaging', '18-96026932-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (37, 'Harber LLC', 'Procter & Gamble Manufacturing Company', '86-49746529-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (38, 'Boyer and Sons', 'Creation''s Garden Natural Products, Inc', '95-61492803-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (39, 'Hagenes and Sons', 'Alcon Laboratories, Inc.', '97-11353138-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (40, 'Rutherford and Sons', 'Bath & Body Works, Inc.', '12-02589748-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (41, 'Russel Group', 'Eight and Company', '01-63688783-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (42, 'Kemmer LLC', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', '06-24458866-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (43, 'Sanford Inc', 'AMI Cosmetic Co.,Ltd.', '86-36639606-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (44, 'Pollich, Feeney and Heidenreich', 'Melaleuca Inc.', '95-23102146-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (45, 'Hyatt and Sons', 'Physicians Total Care, Inc.', '76-84707251-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (46, 'O''Hara, Mayer and Hilll', 'Health Care Products', '49-31586918-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (47, 'Hintz, Grant and Schroeder', 'ALK-Abello, Inc.', '18-22507746-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (48, 'Rutherford Group', 'Graceway Pharmaceuticals, LLC', '07-79943217-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (49, 'Buckridge-Corkery', 'philosophy', '80-48390967-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (50, 'Bashirian, Russel and Hackett', 'Ionx d/b/a HelloLife, LLC', '37-25969621-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (51, 'Legros-Rogahn', 'REMEDYREPACK INC.', '81-67131234-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (52, 'Feil, Ledner and Steuber', 'King Bio Inc.', '35-80938507-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (53, 'Rempel LLC', 'Northstar Rx LLC', '39-85610089-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (54, 'Stracke, Skiles and Wilderman', 'Chain Drug Marketing Association', '57-29576670-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (55, 'Johns and Sons', 'Preferred Pharmaceuticals, Inc.', '46-37287819-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (56, 'Friesen-Bartoletti', 'Wockhardt USA LLC.', '02-45131716-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (57, 'Hoppe-Koss', 'Aurobindo Pharma Limited', '31-76288513-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (58, 'Dare, Hayes and Leuschke', 'Rite Aid', '92-88142462-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (59, 'Becker LLC', 'Greenbrier International, Inc.', '84-29528058-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (60, 'Graham and Sons', 'K.N.Life Co., Ltd.', '54-73233863-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (61, 'Marvin LLC', 'Rohto-Mentholatum (Vietnam) Co. Ltd.', '03-68152457-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (62, 'Heller Inc', 'Insight Pharmaceuticals LLC', '33-06407755-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (63, 'Sanford, Labadie and Spencer', 'H E B', '44-56920671-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (64, 'Swift and Sons', 'Bryant Ranch Prepack', '55-47347903-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (65, 'Bins, Collier and Rippin', 'Rebel Distributors Corp.', '03-16915051-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (66, 'Mitchell-Okuneva', 'InterMune, Inc.', '26-40036114-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (67, 'Harvey-Koepp', 'ALK-Abello, Inc.', '42-80370871-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (68, 'Schaden Inc', 'Uriel Pharmacy Inc.', '64-86817475-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (69, 'Jenkins-Bailey', 'Bare Escentuals Beauty Inc.', '60-56117239-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (70, 'Corwin Inc', 'REMEDYREPACK INC.', '01-01998272-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (71, 'Botsford-Brekke', 'Similasan Corporation', '70-45722346-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (72, 'Larkin and Sons', 'A-S Medication Solutions LLC', '26-13038879-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (73, 'Flatley, Wisozk and Borer', 'Dispensing Solutions, Inc.', '51-79100334-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (74, 'Lueilwitz LLC', 'MARKSANS PHARMA LIMITED', '32-26851470-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (75, 'Daniel, Bode and Upton', 'Cardinal Health', '55-15042159-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (76, 'Wiza Group', 'Reckitt Benckiser LLC', '14-30178413-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (77, 'Nader Group', 'Sandoz Inc', '56-42747746-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (78, 'Crooks-Larkin', 'Hi-Tech Pharmacal Co., Inc.', '90-87241147-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (79, 'Gorczany-Effertz', 'Fresenius Kabi USA, LLC', '77-68898164-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (80, 'Barton, Padberg and Runte', 'International Beauty Exchange', '41-75567299-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (81, 'Sanford-Klein', 'Mylan Pharmaceuticals Inc.', '06-71592614-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (82, 'Okuneva-Morissette', 'L Perrigo Company', '33-35633456-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (83, 'McDermott, Schultz and Tromp', 'American Health Packaging', '02-07845481-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (84, 'Rau, Berge and Pacocha', 'Aphena Pharma Solutions - Tennessee, LLC', '83-00891912-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (85, 'Jacobs, Schmidt and Wolf', 'AvKARE, Inc.', '34-97898900-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (86, 'O''Reilly Group', 'Supervalu Inc', '09-83503347-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (87, 'Tillman, Tillman and Beer', 'Cephalon, Inc.', '69-54991982-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (88, 'Hyatt LLC', 'Allermed Laboratories, Inc.', '67-96827520-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (89, 'Cole Inc', 'Dispensing Solutions, Inc.', '84-23899314-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (90, 'Jaskolski, Schultz and Rogahn', 'Par Pharmaceutical Inc.', '26-22014570-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (91, 'Langosh, Mann and Zulauf', 'Aero-Med Ltd', '24-57665700-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (92, 'Franecki and Sons', 'Natural Health Supply', '17-88280904-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (93, 'Klocko-Nienow', 'Cardinal Health', '24-72433026-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (94, 'Weimann-Fisher', 'Laboratoires Clarins S.A.', '84-69693636-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (95, 'Murazik, Kris and Boyle', 'AstraZeneca Pharmaceuticals LP', '86-33978816-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (96, 'Prohaska Inc', 'Meijer Distribution Inc', '77-14721719-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (97, 'Brakus and Sons', 'PD-Rx Pharmaceuticals, Inc.', '75-88898642-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (98, 'Zieme, Bode and Ritchie', 'EMD Serono, Inc.', '81-28459042-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (99, 'Jacobson Group', 'Aidance Skincare & Topical Solutions, LLC', '84-51190836-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (100, 'Stroman, Hermiston and Runolfsdottir', 'Nelco Laboratories, Inc.', '13-97770923-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (101, 'Schumm-Franecki', 'Bryant Ranch Prepack', '77-20021844-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (102, 'Hyatt, Armstrong and Adams', 'King Bio Inc.', '06-42437829-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (103, 'Hyatt-Stark', 'Novartis Pharmaceuticals Corporation', '16-15368374-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (104, 'Shanahan-Predovic', 'KAS Direct LLC dba BabyGanics', '08-19690762-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (105, 'Braun, Smith and Mueller', 'Mylan Institutional Inc.', '43-58000997-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (106, 'Jaskolski Group', 'Roxane Laboratories, Inc', '59-52968114-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (107, 'Wehner LLC', 'Genuine First Aid LLC', '23-10743314-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (108, 'Ankunding-Leuschke', 'H.J. Harkins Company, Inc.', '57-88812289-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (109, 'Kulas LLC', 'Laboratoires Clarins S.A.', '54-70342950-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (110, 'O''Keefe, Hagenes and Roob', 'ALK-Abello, Inc.', '61-62263260-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (111, 'Schultz and Sons', 'ANIP Acquisition Company', '56-58091553-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (112, 'Pfannerstill and Sons', 'Aire-Master of America, Inc.', '86-98530911-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (113, 'Jacobs, Senger and Kihn', 'sanofi-aventis U.S. LLC', '92-76606309-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (114, 'Oberbrunner, Flatley and Weimann', 'Ventura Corporation LTD', '90-93594188-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (115, 'Luettgen-Paucek', 'Wakefern Food Corporation', '86-92222320-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (116, 'Boyle-Thompson', 'CARDINAL HEALTH', '22-03661049-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (117, 'Corkery-Gleichner', 'Publix Super Markets Inc', '02-36279514-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (118, 'Wilkinson, Nikolaus and Greenfelder', 'Amerisource Bergen', '99-36764235-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (119, 'Johns, McGlynn and Schinner', 'Merle Norman Cosmetics, Inc', '36-08651602-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (120, 'Morar, Torp and Ferry', 'Ventura Corporation (San Juan, P.R)', '77-52330849-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (121, 'Kreiger-Powlowski', 'Nova Homeopathic Therapeutics, Inc.', '52-09827419-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (122, 'Muller and Sons', 'REMEDYREPACK INC.', '26-08166788-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (123, 'Sipes-Lind', 'Pharmacia and Upjohn Company', '24-19834829-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (124, 'McDermott LLC', 'Chantecaille Beaute Inc', '70-08928033-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (125, 'Wintheiser, Langosh and Hammes', 'Allergy Laboratories, Inc.', '63-45467456-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (126, 'Wintheiser, Hamill and Doyle', 'HANGZHOU MINO DAILY CHEMICALS CO.LTD.', '38-24220581-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (127, 'Rath Inc', 'Amerisource Bergen', '25-39889802-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (128, 'Maggio, Kovacek and Huel', 'Nnodum Pharmaceuticals', '95-07612846-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (129, 'Hilll, Schowalter and Gusikowski', 'CVS Pharmacy', '03-06972809-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (130, 'Hane-Gusikowski', 'Bradford Soap Works, Inc.', '18-31532237-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (131, 'O''Reilly Inc', 'Cadila Healthcare Limited', '65-60359138-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (132, 'Wilderman-Effertz', 'Uriel Pharmacy Inc', '54-65769868-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (133, 'Homenick and Sons', 'Physicians Total Care, Inc.', '39-71792187-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (134, 'Boehm, Parker and Larson', 'American Health Packaging', '42-64809993-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (135, 'Rath Inc', 'Pearson Dental', '78-58656671-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (136, 'Ziemann-Shields', 'Hospira, Inc.', '15-53652512-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (137, 'Hahn-Crona', 'A P J Laboratories Limited', '31-89029974-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (138, 'Toy, Gaylord and Mraz', 'Colgate-Palmolive Company', '71-73524240-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (139, 'Labadie Inc', 'Dermarite Industries LLC', '60-86501475-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (140, 'Lebsack-Mraz', 'Waxie Sanitary Supply', '71-56302392-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (141, 'Koepp-Kozey', 'Greenstone LLC', '79-72185175-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (142, 'Prosacco-Hilpert', 'Biocosmetic Research Labs', '13-82935171-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (143, 'King, Kassulke and Schroeder', 'PD-Rx Pharmaceuticals, Inc.', '62-63274987-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (144, 'Hackett, Labadie and Ratke', 'Physicians Total Care, Inc.', '85-50635567-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (145, 'Haley-Batz', 'Blistex Inc.', '10-62870984-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (146, 'Durgan LLC', 'McKesson', '39-63308487-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (147, 'Rolfson-Gorczany', 'Pack Pharmaceuticals, LLC', '42-97883243-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (148, 'Gaylord, McDermott and Zboncak', 'Major Pharmaceuticals', '00-74432414-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (149, 'Doyle, Flatley and Gibson', 'Carilion Materials Management', '91-63159703-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (150, 'Kunze-Gislason', 'King Bio Inc.', '23-81629445-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (151, 'Reichel Inc', 'AMERICAN SALES', '47-13364510-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (152, 'Stoltenberg-Barton', 'Hisamitsu Pharmaceutical Co., Inc.', '33-35336017-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (153, 'Bergnaum and Sons', 'Safetec of America, Inc.', '49-79881716-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (154, 'Schroeder and Sons', 'Personal Care Products', '52-37818705-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (155, 'Lebsack-Boyle', 'Top Care', '37-91311108-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (156, 'Jaskolski-Harber', 'Rite Aid Corporation', '99-10843713-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (157, 'Gaylord, Prosacco and Dickinson', 'Alaven Pharmaceutical LLC', '06-87457988-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (158, 'Zieme Inc', 'LABORATORIO MAGNACHEM INTERNATIONAL SRL', '44-12555006-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (159, 'Mann-Rogahn', 'ALK-Abello, Inc.', '25-91573160-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (160, 'Abshire, White and Hagenes', 'Jiangsu Province JianErKang Medical Dressing Co. ,Ltd.', '67-19673804-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (161, 'Hahn, Jenkins and Wiegand', 'Cardinal Health', '43-14520525-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (162, 'Thompson and Sons', 'WIZCOZ CORPORATION LTD', '75-35593396-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (163, 'Mitchell, Cummings and Erdman', 'Cadila Pharmaceuticals Limited', '41-60021346-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (164, 'Pacocha Group', 'AvPAK', '00-81128459-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (165, 'Hamill-Mayer', 'McKesson Contract Packaging', '10-04440204-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (166, 'Jacobi-Heidenreich', 'Ecolab Inc.', '17-07541175-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (167, 'Mills-Daniel', 'Mylan Pharmaceuticals Inc.', '97-04974170-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (168, 'Kassulke-Howe', 'International Beauty Exchange', '51-25597581-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (169, 'Ziemann-Strosin', 'Cadila Healthcare Limited', '38-45731679-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (170, 'Rippin, Murray and Heathcote', 'Accra-Pac, Inc.', '51-83964087-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (171, 'Runolfsson-Glover', 'Preferred Pharmaceuticals, Inc.', '67-96368848-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (172, 'Gerlach Inc', 'WOCKHARDT LIMITED', '99-45840508-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (173, 'Grimes, Herzog and Schaefer', 'Antigen Laboratories, Inc.', '55-86475218-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (174, 'Konopelski and Sons', 'Personal Care Products', '34-06435336-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (175, 'Torphy-Predovic', 'Fresenius Kabi USA, LLC', '90-11384726-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (176, 'Krajcik, Hartmann and Bailey', 'Geri-Care Pharmaceuticals, Corp', '92-87746700-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (177, 'Kutch LLC', 'Safeway', '17-67237174-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (178, 'Kuhlman, Stiedemann and Weber', 'REMEDYREPACK INC.', '93-85842040-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (179, 'Hahn-Lang', 'DOLGENCORP INC', '60-44406372-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (180, 'Becker Group', 'HomeopathyStore.com', '74-88670847-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (181, 'Hane-Gusikowski', 'Nelco Laboratories, Inc.', '10-90918246-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (182, 'Wilderman-Murray', 'PD-Rx Pharmaceuticals, Inc.', '95-08198498-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (183, 'Bernier-Barton', 'sanofi-aventis U.S. LLC', '57-77048438-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (184, 'Heller Group', 'West-Ward Pharmaceutical Corp.', '23-20388432-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (185, 'Paucek, Stark and Kassulke', 'ALK-Abello, Inc.', '03-08991066-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (186, 'Koss-Roob', 'REMEDYREPACK INC.', '79-77972037-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (187, 'Robel-Blick', 'Uriel Pharmacy Inc.', '11-34430918-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (188, 'Lehner, Welch and Grimes', 'Avon Products, Inc', '02-60072814-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (189, 'Dickens-Lubowitz', 'PD-Rx Pharmaceuticals, Inc.', '00-55200486-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (190, 'Kihn-Muller', 'Wal-Mart Stores, Inc.', '32-41632263-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (191, 'Hodkiewicz-Bode', 'Teva Pharmaceuticals USA Inc', '44-87941977-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (192, 'Bradtke-McDermott', 'Hebei Yihoucheng Commodity Co.,Ltd.', '06-07677359-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (193, 'Rogahn Group', 'Healthy Accents (DZA Brands, LLC)', '69-32091829-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (194, 'Kuvalis-Osinski', 'Energetix Corp', '31-33938739-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (195, 'Mraz-Jacobi', 'Uriel Pharmacy Inc.', '59-39436818-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (196, 'DuBuque Inc', 'CVS Pharmacy', '17-25414220-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (197, 'Tromp-Stoltenberg', 'Cardinal Health', '38-53753232-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (198, 'Spinka, Wisoky and Miller', 'RITE AID CORPORATION', '22-19223980-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (199, 'Funk and Sons', 'Valeant Pharmaceuticals North America LLC', '59-04010645-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (200, 'Gusikowski-Spinka', 'UDL Laboratories, Inc.', '06-26445680-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (201, 'Metz Inc', 'Phoenix Pharmaceutical, Inc.', '82-53702130-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (202, 'Osinski LLC', 'Global Pharmaceuticals, Division of Impax Laboratories Inc.', '77-16296698-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (203, 'Kub, Ledner and Larson', 'Molton Brown LTD (UK)', '84-98249833-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (204, 'Bauch-Cassin', 'Perrigo New York Inc', '98-32196225-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (205, 'Hermann Inc', 'Preferred Pharmaceuticals, Inc', '69-45690605-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (206, 'Oberbrunner-Okuneva', 'Nelco Laboratories, Inc.', '46-17379093-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (207, 'Crist LLC', 'Rebel Distributors Corp.', '58-53934421-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (208, 'Stokes LLC', 'MSD Consumer Care, Inc.', '49-10936514-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (209, 'Kirlin, Walter and O''Keefe', 'Preferred Pharmaceuticals, Inc.', '05-53288518-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (210, 'Price, Hilpert and Rempel', 'TOP CARE (Topco Associates LLC)', '30-05884210-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (211, 'Kovacek-Jacobson', 'Perrigo New York Inc', '44-22691971-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (212, 'Homenick Inc', 'Sun Pharmaceutical Industries Limited', '00-31638306-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (213, 'Hessel-Sporer', 'Kmart Corporation', '37-39296948-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (214, 'Osinski LLC', 'Physicians Total Care, Inc.', '12-27264566-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (215, 'Grimes, Blanda and Kshlerin', 'Owens and Minor', '26-38365320-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (216, 'Paucek, Prohaska and Bins', 'Teva Pharmaceuticals USA Inc', '16-15846576-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (217, 'Kling-Jenkins', 'NCS HealthCare of KY, Inc dba Vangard Labs', '96-05097350-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (218, 'Lehner-Rutherford', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', '39-39249368-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (219, 'Ortiz LLC', 'Dr. Reddy''s Laboratories Limited', '24-34673276-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (220, 'Effertz-Spencer', 'Ascend Laboratories, LLC', '89-86480732-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (221, 'Fadel-Erdman', 'UIHC-P E T IMAGING CENTER', '78-48669144-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (222, 'Treutel, Mohr and Medhurst', 'OMP, INC.', '43-09351562-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (223, 'Ritchie, Bradtke and Bogan', 'Walgreen Company', '32-72490903-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (224, 'Ratke and Sons', 'ASSURED / DOLLAR TREE (Greenbrier International, Inc.)', '62-99812492-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (225, 'Nienow-Weber', 'Incyte Corporation', '64-15968392-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (226, 'White and Sons', 'Publix Super Markets Inc', '45-30761101-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (227, 'Cole LLC', 'Aphena Pharma Solutions - Tennessee, LLC', '84-68598536-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (228, 'Jakubowski Inc', 'Preferred Pharmaceuticals, Inc.', '71-15479118-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (229, 'Bergstrom, Koelpin and Schowalter', 'American Health Packaging', '18-76632532-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (230, 'Batz-O''Reilly', 'Pack Pharmaceuticals LLC', '53-83796311-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (231, 'Huel Inc', 'Clinical Solutions Wholesale', '92-41287021-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (232, 'MacGyver, Murazik and Franecki', 'WALGREEN CO.', '68-52882751-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (233, 'Maggio-Ortiz', 'Barona Co., Ltd', '96-70043202-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (234, 'Runolfsson-Witting', 'The Wellness Center', '83-05252239-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (235, 'Klocko LLC', 'BioActive Nutritional, Inc.', '93-51663940-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (236, 'Gaylord Inc', 'NCS HealthCare of KY, Inc dba Vangard Labs', '37-97541037-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (237, 'Bins, Abbott and Cormier', 'CareStream Health, Inc.', '87-34294685-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (238, 'Labadie, Bins and Feeney', 'ABC Compounding Co., Inc.', '41-12369166-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (239, 'Dickens, Okuneva and Bartoletti', 'Neutrogena Corporation', '91-67166006-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (240, 'Lehner, Zemlak and Okuneva', 'Mylan Pharmaceuticals Inc.', '40-02592577-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (241, 'Bernier, Schiller and Heller', 'Aidance Skincare & Topical Solutions, LLC', '94-55757896-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (242, 'Olson, Windler and Smith', 'REMEDYREPACK INC.', '78-50046465-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (243, 'Nikolaus-Brown', 'Blacksmith Brands, Inc.', '90-20200368-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (244, 'Denesik LLC', 'Mylan Pharmaceuticals Inc.', '85-90605257-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (245, 'Hyatt Inc', 'Guerlain', '30-29370277-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (246, 'Crooks and Sons', 'Humanwell PuraCap Pharmaceutical (Wuhan), Ltd.', '61-58727577-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (247, 'Hegmann-Fisher', 'Marco Pharma International LLC.', '07-13151336-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (248, 'Wuckert-Cummings', 'Glenmark Generics, Inc', '72-56740307-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (249, 'Sanford Inc', 'Nelco Laboratories, Inc.', '55-34943981-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (250, 'Davis LLC', 'Bayer HealthCare Pharmaceuticals Inc.', '60-12854221-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (251, 'Streich-Turner', 'Nelco Laboratories, Inc.', '35-57359724-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (252, 'Ondricka Inc', 'HyVee Inc', '56-55814197-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (253, 'Runte-Jast', 'Apotex Corp.', '92-55082955-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (254, 'Volkman LLC', 'Afaxys Inc.', '99-46656368-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (255, 'Breitenberg-Kozey', 'NCS HealthCare of KY, Inc dba Vangard Labs', '47-96657264-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (256, 'Gibson Inc', 'Jubilant HollisterStier LLC', '92-53709862-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (257, 'MacGyver, Conn and Kunze', 'My Habitat Brands LLC', '37-10543343-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (258, 'Willms Inc', 'Hospira, Inc.', '72-69009007-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (259, 'Koelpin-Nienow', 'NCS HealthCare of KY, Inc dba Vangard Labs', '27-81557208-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (260, 'Ortiz Group', 'Seton Pharmaceuticals', '83-71191366-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (261, 'Klein and Sons', 'Vagabond Welding Supply', '81-76323915-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (262, 'McGlynn Inc', 'Apotheca Company', '98-31474476-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (263, 'Lesch, Aufderhar and Hagenes', 'Par Pharmaceutical, Inc.', '56-94025197-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (264, 'Kuhic, Rowe and Marquardt', 'Bryant Ranch Prepack', '81-29948449-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (265, 'Corwin-Stanton', 'Antigen Laboratories, Inc.', '87-44854188-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (266, 'Yost Group', 'Wal-Mart Stores Inc', '83-66764506-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (267, 'Kulas LLC', 'Cardinal Health, Inc', '01-18103486-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (268, 'Rolfson-Bechtelar', 'NCH Corporation', '37-17306059-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (269, 'Wuckert-Sipes', 'AstraZeneca LP', '34-74773532-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (270, 'Gutkowski, Okuneva and Willms', 'Conopco Inc. d/b/a Unilever', '17-46337016-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (271, 'Treutel-Schulist', 'NCS HealthCare of KY, Inc dba Vangard Labs', '88-43414505-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (272, 'Reinger-Bauch', 'Supervalu Inc', '44-10824452-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (273, 'Schmeler, Brekke and Roob', 'Clinical Solutions', '19-36484292-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (274, 'Smitham, Weissnat and Breitenberg', 'Otsuka America Pharmaceutical, Inc.', '00-35980037-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (275, 'Hauck-Kessler', 'AmerisourceBergen Drug Corporation (Good Neighbor Pharmacy) 24385', '48-21082843-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (276, 'Rolfson LLC', 'CHANEL PARFUMS BEAUTE', '07-30633027-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (277, 'Keeling Inc', 'MAJOR PHARMACEUTICALS INC', '08-76954177-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (278, 'Borer Inc', 'H and P Industries, Inc. dba Triad Group', '83-62344974-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (279, 'Kunde-Cremin', 'Cardinal Health', '27-99164728-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (280, 'McKenzie, Mohr and Frami', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', '32-74512139-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (281, 'Langworth, Jacobi and Beier', 'PD-Rx Pharmaceuticals, Inc.', '98-57457239-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (282, 'Braun-Wunsch', 'Kroger Co', '76-33032908-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (283, 'Hoppe Inc', 'Cherry Hill Sales Co', '73-24939160-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (284, 'Olson LLC', 'Rebel Distributors Corp', '62-41561651-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (285, 'Kohler LLC', 'Best Choice', '74-92696253-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (286, 'Blick, Bruen and Keebler', 'Warner Chilcott Pharmaceuticals Inc.', '92-67068028-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (287, 'Reichert Group', 'Elizabeth Arden, Inc', '97-67042017-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (288, 'Deckow LLC', 'Prestige Brands Holdings, Inc.', '51-04906523-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (289, 'Klocko, Gaylord and Skiles', 'Mylan Pharmaceuticals Inc.', '09-30082852-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (290, 'Corwin-Schuppe', 'Tec Laboratories, Inc.', '22-29091104-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (291, 'Kessler-Douglas', 'Golden Sun DBA Newhall Laboratories', '24-88956724-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (292, 'McLaughlin, Beahan and Champlin', 'Rebel Distributors Corp', '28-40660942-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (293, 'Grant LLC', 'APP Pharmaceuticals, LLC', '11-88343167-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (294, 'Reichert, Kozey and Ullrich', 'Lehigh Valley Technologies, Inc.', '21-51300899-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (295, 'Murray Group', 'Aidarex Pharmaceuticals LLC', '24-81772691-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (296, 'Lueilwitz Inc', 'Neutrogena Corporation', '31-89595225-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (297, 'Torphy, Stokes and Murazik', 'BioActive Nutritional, Inc.', '37-06637067-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (298, 'Muller and Sons', 'Watson Pharma, Inc.', '84-54026305-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (299, 'Larson, Morissette and Lockman', 'Mylan Institutional Inc.', '88-75860191-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (300, 'Wisoky-Adams', 'Antigen Laboratories, Inc.', '96-48372830-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (301, 'Sauer, Purdy and Gerhold', 'Pharmaplast SAE', '93-04607520-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (302, 'Wolff-Sanford', 'Breckenridge Pharmaceutical, Inc', '85-79287574-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (303, 'Zboncak and Sons', 'Nehemiah Manufacturing', '83-87270150-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (304, 'Crooks Inc', 'TYA Pharmaceuticals', '16-98818404-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (305, 'Mosciski-Kilback', 'Fenwal, Inc.', '15-24949285-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (306, 'Paucek, Monahan and Ratke', 'Mallinckrodt, Inc.', '77-72318942-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (307, 'Yundt, Fadel and Legros', 'ABCO Laboratories, Inc.', '99-56239515-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (308, 'Mills LLC', 'ALK-Abello, Inc.', '83-54598414-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (309, 'Gutmann Group', 'L. Perrigo Company', '31-06635376-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (310, 'Berge, Sauer and Towne', 'GOJO Industries, Inc.', '78-44128521-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (311, 'Hackett-Bayer', 'Proficient Rx LP', '44-37759315-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (312, 'Lang and Sons', 'Aurobindo Pharma Limited', '86-17116744-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (313, 'Orn-Runolfsdottir', 'BCM Cosmetique SAS', '86-68607820-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (314, 'Volkman-Hahn', 'Autumn Harp, Inc', '13-17451372-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (315, 'Schaden-Cormier', 'Nelco Laboratories, Inc.', '55-57207223-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (316, 'Hand, Rowe and Batz', 'Watson Laboratories, Inc.', '01-72653388-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (317, 'Altenwerth Inc', 'Asclemed USA, Inc.', '16-74588242-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (318, 'Schaefer and Sons', 'Elishacoy Co., Inc.', '24-12168873-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (319, 'Hickle-Hilpert', 'Andalou naturals', '70-80624108-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (320, 'Cartwright, Walsh and Ullrich', 'PD-Rx Pharmaceuticals, Inc.', '19-17580927-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (321, 'Strosin Group', 'Nelco Laboratories, Inc.', '98-08578398-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (322, 'Jast Inc', 'Major Pharmeceuticals', '40-01890889-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (323, 'Hackett, Hackett and Emard', 'Meijer Distribution Inc', '21-38268880-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (324, 'Boyle, O''Reilly and Doyle', 'Antigen Laboratories, Inc.', '18-25744780-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (325, 'Emard, Bosco and Wunsch', 'McKesson (Health Mart)', '66-62798030-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (326, 'Fay Inc', 'American Health Packaging', '35-58650966-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (327, 'Towne-Veum', 'Publix Supermarkets, Inc.', '96-08380525-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (328, 'Weimann, Frami and Beatty', 'ACELLA PHARMACEUTICALS', '90-20615967-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (329, 'Haag Group', 'Lake Erie Medical DBA Quality Care Products LLC', '13-83269515-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (330, 'Spencer LLC', 'ENCHANTE ACCESSORIES INC.', '15-41723153-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (331, 'O''Conner-Windler', 'Deb USA, Inc.', '83-71601976-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (332, 'Zieme and Sons', 'AvKARE, Inc.', '91-32474604-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (333, 'Gaylord, Auer and Schultz', 'ARMY AND AIR FORCE EXCHANGE SERVICE', '21-81019392-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (334, 'Conroy, Cassin and Hoeger', 'Wockhardt Limited', '83-30890400-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (335, 'Cartwright, Schulist and Doyle', 'Physicians Total Care, Inc.', '63-00974860-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (336, 'Smith-Walter', 'REMEDYREPACK INC.', '97-24993916-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (337, 'Gibson and Sons', 'Sagent Pharmaceuticals', '27-12054231-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (338, 'Glover Inc', 'Conopco Inc. d/b/a Unilever', '49-11380216-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (339, 'Eichmann, Homenick and Beahan', 'CVS Pharmacy, Inc.', '35-25647709-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (340, 'Windler, Huels and Wolf', 'Supervalu Inc', '12-52732591-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (341, 'Grimes Group', 'General Injectables & Vaccine, Inc', '92-19139586-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (342, 'Daugherty, Koss and Simonis', 'Fred''s Inc.', '92-95897012-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (343, 'McCullough-Bechtelar', 'AstraZeneca LP', '82-15776044-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (344, 'Gottlieb, Hyatt and Huel', 'Preferred Pharmaceuticals, Inc.', '02-73800350-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (345, 'Barton, Hagenes and Yost', 'Xiamen Anna Global Co., Ltd', '69-04651379-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (346, 'Ratke Group', 'Bare Escentuals Beauty Inc.', '12-60505361-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (347, 'Murphy LLC', 'Valu Merchandisers Company', '05-00637450-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (348, 'Pfannerstill-Terry', 'Sun Pharma Global Inc.', '29-85918662-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (349, 'Baumbach-Lesch', 'AstraZeneca Pharmaceuticals LP', '08-47459819-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (350, 'Jenkins Inc', 'RITE AID CORPORATION', '68-67204082-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (351, 'Bechtelar LLC', 'WHITE MANUFACTURING INC. DBA MICRO WEST', '77-36577721-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (352, 'Kris-Weber', 'Ventura Corporation LTD', '46-37644759-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (353, 'Dach Inc', 'Vertical Pharmaceuticals, Inc.', '22-17504982-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (354, 'Blanda-Hickle', 'AMOREPACIFIC', '30-52449886-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (355, 'Abernathy LLC', 'Elizabeth Arden, Inc', '22-41893286-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (356, 'Reichert-Zulauf', 'BioActive Nutritional', '58-70968480-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (357, 'Becker-Grant', 'Guthy-Renker LLC', '71-64889725-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (358, 'Littel, Reichert and Brown', 'Fresenius Medical Care North America', '13-20922202-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (359, 'Miller-Simonis', 'The Pepsom Group, Inc.', '25-02990167-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (360, 'Marquardt LLC', 'Neutrogena Corporation', '16-53110351-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (361, 'Lind, Sanford and Abshire', 'Physicians Total Care, Inc.', '35-03057918-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (362, 'Stroman-Nitzsche', 'BioActive Nutritional, Inc', '02-03063598-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (363, 'Gleichner-Frami', 'Greenstone LLC', '03-51121718-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (364, 'Hills-Fritsch', 'UNITED EXCHANGE CORP.', '31-78719683-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (365, 'Kuhlman LLC', 'Nelco Laboratories, Inc.', '22-38806427-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (366, 'Hilpert, Feest and Beahan', 'Small World Trading Company', '15-14803757-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (367, 'Rau-Prohaska', 'Indiana Botanic Gardens', '80-08461532-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (368, 'Muller-Cummings', 'Lake Erie Medical DBA Quality Care Products LLC', '92-72996753-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (369, 'Larson-Reynolds', 'Antigen Laboratories, Inc.', '86-78665327-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (370, 'Bailey, Leannon and Kris', 'Hetero Drugs Ltd.,', '03-50361234-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (371, 'Toy, Stokes and Zulauf', 'State of Florida DOH Central Pharmacy', '27-51132474-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (372, 'Fahey-Yundt', 'Dr. Reddy''s Laboratories Limited', '62-64928645-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (373, 'Satterfield-Crooks', 'Aidance Skincare & Topical Solutions, LLC', '76-33739968-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (374, 'Graham LLC', 'Mylan Pharmaceuticals Inc.', '08-35220689-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (375, 'Russel, Dickinson and Lehner', 'PD-Rx Pharmaceuticals, Inc.', '65-34606745-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (376, 'Kuhic-Connelly', 'Lancaster S.A.M.', '21-90053377-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (377, 'Upton Group', 'Peaceful Mountain, Inc', '04-13107519-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (378, 'Koelpin and Sons', 'AAA Pharmaceutical, Inc.', '76-84789951-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (379, 'Hand, Lakin and Lowe', 'REMEDYREPACK INC.', '57-72235476-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (380, 'Rolfson, Rutherford and Cummings', 'Sandoz Inc', '59-23890124-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (381, 'Armstrong, Jacobi and Stark', 'State of Florida DOH Central Pharmacy', '56-49566215-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (382, 'Lehner Inc', 'GM Pharamceuticals, Inc', '14-04515300-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (383, 'Bergstrom Inc', 'Aidarex Pharmaceuticals LLC', '62-27368140-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (384, 'Lakin, Donnelly and Stokes', 'Rebel Distributors Corp', '86-08253028-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (385, 'Wiegand Group', 'HOMEOLAB USA INC.', '74-47772174-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (386, 'Hauck Group', 'Janssen Cosmetics GmbH', '15-40982731-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (387, 'Ward, Will and Roberts', 'DIRECT RX', '94-89089707-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (388, 'Jerde, Jenkins and Lehner', 'APOLLO HEALTH AND BEAUTY CARE', '76-18624038-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (389, 'Orn, Jacobs and Deckow', 'Aptalis Pharma US, Inc.', '54-60770101-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (390, 'Waelchi Inc', 'Bryant Ranch Prepack', '03-77144433-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (391, 'Zemlak Group', 'Liddell Laboratories, Inc.', '06-07254839-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (392, 'Monahan-Friesen', 'WALGREEN CO.', '89-50887741-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (393, 'Kirlin, Schultz and Daniel', 'Allermed Laboratories, Inc.', '15-10370226-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (394, 'Prohaska, Robel and Jerde', 'Dr. Reddy''s Laboratories Limited', '14-95718704-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (395, 'Davis LLC', 'Best Choice (Valu Merchandisers Company)', '59-07781134-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (396, 'Waelchi-Hilpert', 'Freshorize, Ltd.', '93-27624661-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (397, 'Dickinson Inc', 'Salix Pharmaceuticals, Inc', '83-76388099-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (398, 'Bins, Donnelly and Lynch', 'Parfums Christian Dior', '38-93979032-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (399, 'Ferry Group', 'Unifirst First Aid Corporation', '52-92587038-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (400, 'Torphy-McKenzie', 'Apotex Corp', '70-18964000-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (401, 'Hayes, Jerde and Stark', 'Wal-Mart Stores Inc', '91-30933734-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (402, 'Bernhard Group', 'Pharmaceutical Specialties, Inc.', '14-48706124-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (403, 'Jones, Okuneva and Hahn', 'Carver Korea Co.,Ltd', '46-40136123-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (404, 'Swaniawski-Monahan', 'AvPAK', '78-30020387-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (405, 'Schulist Group', 'Forces of Nature', '79-09694331-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (406, 'Heidenreich Inc', 'Napoleon Perdis Cosmetics, Inc', '16-09855631-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (407, 'Kassulke, Deckow and Gislason', 'Aurobindo Pharma Limited', '54-93630808-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (408, 'Bins, Sipes and Spencer', 'Cardinal Health', '94-16781647-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (409, 'Carroll-Douglas', 'Pekana-Naturheilmittel GmbH', '89-11703551-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (410, 'Wiegand Inc', 'Apotheca Company', '06-70697305-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (411, 'Gutkowski Inc', 'Unifirst First Aid Corporation', '84-28681889-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (412, 'Torp, Wunsch and Conn', 'Ulta', '02-54810275-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (413, 'Stokes, Metz and Hegmann', 'Ventura Corporation (San Juan, P.R)', '51-87920234-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (414, 'Frami Group', 'Stephen L. LaFrance Pharmacy, Inc.', '58-53544867-2', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (415, 'Waelchi LLC', 'Jets, Sets, & Elephants Beauty Corp.', '70-50787353-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (416, 'Kling LLC', 'Dong Sung Pharm. Co., Ltd.', '19-88774563-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (417, 'Maggio, McKenzie and Schultz', 'Uriel Pharmacy Inc.', '87-45801277-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (418, 'Doyle-Torp', 'Macoven Pharmaceuticals', '66-57475162-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (419, 'Collier Inc', 'PD-Rx Pharmaceuticals, Inc.', '28-47658934-4', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (420, 'Brakus LLC', 'Rebel Distributors Corp', '48-49608689-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (421, 'Rice-Douglas', 'AvPAK', '05-50293200-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (422, 'Daniel, Leffler and Gutmann', 'REMEDYREPACK INC.', '69-15488631-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (423, 'Fahey-Osinski', 'Genuine First Aid LLC', '08-68446797-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (424, 'Considine Group', 'Rite Aid Corporation', '69-25956675-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (425, 'Gutmann Group', 'Direct Rx', '09-49604922-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (426, 'Stiedemann, Simonis and Torphy', 'The Wellness Center', '08-01409400-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (427, 'Smitham-Walter', 'Qualitest Pharmaceuticals', '25-08286030-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (428, 'Wilkinson and Sons', 'Cardinal Health', '17-21598510-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (429, 'Mayer-Bechtelar', 'JAFRA COSMETICS INTERNATIONAL', '98-67428046-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (430, 'Goodwin and Sons', 'Rexall', '69-13315349-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (431, 'Zulauf LLC', 'GRIFOLS USA, LLC', '37-41594499-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (432, 'Steuber-Bergstrom', 'Mutual Pharmaceutical Company, Inc.', '38-75345517-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (433, 'Schuster, Corkery and Brakus', 'Dolgencorp, LLC', '51-46551616-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (434, 'Tillman, Borer and Hoppe', 'Antigen Laboratories, Inc.', '09-13015942-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (435, 'Hettinger, Gerhold and Schiller', 'AstraZeneca Pharmaceuticals LP', '16-67703295-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (436, 'Cummings and Sons', 'Hospira, Inc.', '83-58802607-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (437, 'Jones, Kulas and DuBuque', 'Dukal Corporation', '01-79786845-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (438, 'Rempel, Metz and Luettgen', 'WAL-MART STORES INC.', '90-83746513-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (439, 'Hartmann, Hansen and Wiza', 'LernaPharm Loris Inc.', '67-64646924-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (440, 'Ebert-Mann', 'STAT RX USA LLC', '59-47237939-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (441, 'Roob-Gorczany', 'Perrigo New York Inc', '64-25253449-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (442, 'Zulauf, Lesch and Cronin', 'Cardinal Health', '04-47863602-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (443, 'Schneider-Emmerich', 'Rebel Distributors Corp', '13-34628205-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (444, 'Koelpin and Sons', 'Kingdom Animalia, LLC DBA Hourglass Cosmetics', '15-19437813-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (445, 'Murray-Pfeffer', 'Sandoz Inc', '14-06770465-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (446, 'Gorczany, Zemlak and Bogan', 'Pharmics, Inc.', '39-68477721-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (447, 'Mohr, Hansen and Wehner', 'Alert Respiratory Services, Inc.', '87-03339659-5', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (448, 'Crona-Hand', 'Seton Pharmaceuticals', '30-95348806-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (449, 'Labadie, Haag and Crooks', 'MedVantx, Inc.', '65-58690217-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (450, 'Bernhard LLC', 'Allergy Laboratories, Inc.', '66-33125092-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (451, 'Kunde, Frami and Heathcote', 'Western Family Foods Inc', '99-52557356-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (452, 'Stamm Group', 'Newton Laboratories, Inc.', '48-94182129-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (453, 'Kihn-Gutmann', 'Greenstone LLC', '06-11534572-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (454, 'Will Inc', 'Medline Industries, Inc.', '39-79441929-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (455, 'Langosh LLC', 'BDMP, LLC', '53-57513077-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (456, 'Stark, Kling and Metz', 'Nelco Laboratories, Inc.', '36-63080702-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (457, 'Gibson-Metz', 'Macleods Pharmaceuticals Limited', '67-67948530-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (458, 'Koss, Considine and Denesik', 'Island Equipment Company', '67-40719375-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (459, 'Boyle-Hahn', 'Fusion Brands', '86-36422371-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (460, 'Bogan Group', 'Go Smile, Inc.', '79-49541373-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (461, 'Ledner Group', 'Proficient Rx LP', '77-32229600-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (462, 'Morissette Inc', 'Richmond Division of Wyeth', '54-70608119-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (463, 'Huel, Kautzer and Kautzer', 'Safetec of America, Inc.', '82-95596949-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (464, 'Davis-King', 'NeoStrata Company Inc.', '20-98974189-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (465, 'Considine, Bernhard and O''Reilly', 'L''Oreal USA Products Inc', '72-51588062-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (466, 'Aufderhar, Smith and Hessel', 'Barr Laboratories, Inc.', '93-88909437-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (467, 'Waelchi-Hickle', 'Nelco Laboratories, Inc.', '29-13561065-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (468, 'Hansen, Block and Boehm', 'Select Brand', '60-75237174-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (469, 'Gibson, Cronin and Nicolas', 'DRAXIMAGE LLC', '92-16838992-9', 'retail');
insert into organization (id, name, legalName, cuit, role) values (470, 'Runolfsson, Treutel and Hirthe', 'Carilion Materials Management', '26-79244170-9', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (471, 'Hammes-Kovacek', 'Carilion Materials Management', '25-62596789-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (472, 'McKenzie-Connelly', 'PSS World Medical', '99-88811857-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (473, 'Marquardt-Bernhard', 'Dispensing Solutions, Inc.', '02-04709807-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (474, 'Stokes-Muller', 'CVS Pharmacy', '03-32447350-8', 'retail');
insert into organization (id, name, legalName, cuit, role) values (475, 'Schuppe, Strosin and Stroman', 'AIRGAS USA, LLC', '89-08490698-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (476, 'Tromp-Lehner', 'H E B', '23-65927126-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (477, 'Hettinger, Gorczany and Zemlak', 'Cangene bioPharma Inc.', '76-81172760-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (478, 'Schulist-McKenzie', 'Actavis Elizabeth LLC', '75-46525204-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (479, 'Haley and Sons', 'Uriel Pharmacy Inc.', '05-18576698-1', 'retail');
insert into organization (id, name, legalName, cuit, role) values (480, 'Orn, Hane and Rowe', 'Precision Dose Inc.', '69-36158443-3', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (481, 'Ratke Inc', 'REMEDYREPACK INC.', '41-65817613-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (482, 'Mayer-Dickinson', 'RiteAid', '51-51403840-7', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (483, 'Pfeffer and Sons', 'Kroger Company', '32-05703639-0', 'retail');
insert into organization (id, name, legalName, cuit, role) values (484, 'Buckridge-Stehr', 'Sandoz Inc', '04-47208088-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (485, 'Wintheiser, Gerhold and Crooks', 'PD-Rx Pharmaceuticals, Inc.', '76-44227629-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (486, 'Kovacek-Mayert', 'Bryant Ranch Prepack', '93-31109447-8', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (487, 'Corwin LLC', 'ENERGIZER PERSONAL CARE LLC', '25-75161091-5', 'retail');
insert into organization (id, name, legalName, cuit, role) values (488, 'Reynolds Group', 'Uriel Pharmacy Inc', '65-71925024-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (489, 'Carroll, Rodriguez and Heller', 'Western Family Foods, Inc.', '06-53128710-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (490, 'Rice, Bahringer and Baumbach', 'Houston Cyclotron Partners LP dba Cyclotope', '49-88360702-6', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (491, 'Roberts Inc', 'West-Ward Pharmaceutical Corp', '83-23062604-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (492, 'Cormier Inc', 'Prasco Laboratories', '75-84067794-6', 'retail');
insert into organization (id, name, legalName, cuit, role) values (493, 'Littel-Nolan', 'Dynamic Pharmaceuticals Inc.', '34-16675707-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (494, 'Morissette, Carter and Marks', 'A-S Medication Solutions LLC', '06-16752788-7', 'retail');
insert into organization (id, name, legalName, cuit, role) values (495, 'Nolan and Sons', 'CVS PHARMACY', '30-55065087-4', 'retail');
insert into organization (id, name, legalName, cuit, role) values (496, 'Yundt, Huel and Hauck', 'Cardinal Health', '73-41579514-2', 'retail');
insert into organization (id, name, legalName, cuit, role) values (497, 'Mante, McGlynn and Greenholt', 'CLINIQUE LABORATORIES INC', '70-41551205-1', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (498, 'Hane Group', 'BioActive Nutritional, Inc.', '82-66895498-0', 'supplier');
insert into organization (id, name, legalName, cuit, role) values (499, 'Yost-Christiansen', 'Mission Hills S.A de C.V', '19-14491730-3', 'retail');
insert into organization (id, name, legalName, cuit, role) values (500, 'Casper, Rodriguez and Brakus', 'Uriel Pharmacy Inc.', '30-64066015-7', 'retail');
